import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { ColorModeScript } from "@chakra-ui/react";
import theme from "./ChakraTheme";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ newrecord, children }) {
  return (
    <html lang="en">
      <body style={{ height: "100dvh" }}>
        <ColorModeScript initialColorMode={theme.config.initialColorMode} />
        <Providers>
          {newrecord}
          {children}
        </Providers>
      </body>
    </html>
  );
}
